name: on-pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - 'renovate.json'
      - ".github/workflows/**"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "tests/**"
      - "functions/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v3.0.0
    with:
      examples: |
        [
          { "example": "examples/volumesnapshotstacks/minimal.yaml" },
          { "example": "examples/volumesnapshotstacks/ha.yaml" }
        ]
      api_path: apis/volumesnapshotstacks
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v3.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v3.0.0

  publish:
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v3.0.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
